spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/in28microservice
    username: yasinkaji
    password: Yasin@Kaji0678
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always

  application:
    name: currency-exchange-service
server:
  port: 8000
